OPEN SCHEMA NOAH_JUTZ;

MERGE INTO LOCATION l
USING ST_META_BUNDESTAG_DISTRICTS d
ON l.VOTING_DISTRICT_ID = d.DISTRICT_ID
WHEN MATCHED THEN UPDATE SET l.voting_district_name = d.DISTRICT_NAME, l.state_bundesland = d.STATE_NAME;