OPEN SCHEMA NOAH_JUTZ;

-- Merge

MERGE INTO PARTY t
USING ( SELECT SHORTNAME, MAX(NAME) AS NAME
        FROM ST_META_BUNDESTAG_PARTIES
        GROUP BY SHORTNAME
    ) AS s
ON t.SHORTNAME = s.SHORTNAME
WHEN MATCHED THEN
    UPDATE
    SET FULL_NAME = NAME
WHEN NOT MATCHED THEN
    INSERT
        (SHORTNAME, FULL_NAME)
    VALUES (SHORTNAME, NAME);

UPDATE PARTY
SET VALUE_ID=1,
    VALUE_LABEL='CDU / CSU'
WHERE SHORTNAME = 'union';
UPDATE PARTY
SET VALUE_ID=4,
    VALUE_LABEL='SPD'
WHERE SHORTNAME = 'spd';
UPDATE PARTY
SET VALUE_ID=5,
    VALUE_LABEL='FDP'
WHERE SHORTNAME = 'fdp';
UPDATE PARTY
SET VALUE_ID=6,
    VALUE_LABEL='GRÜNE'
WHERE SHORTNAME = 'gruene';
UPDATE PARTY
SET VALUE_ID=7,
    VALUE_LABEL='PDS, Die Linke'
WHERE SHORTNAME = 'linke';
UPDATE PARTY
SET VALUE_ID=105,
    VALUE_LABEL='ADM - Allianz der Mitte'
WHERE SHORTNAME = 'adm';
UPDATE PARTY
SET VALUE_ID=118,
    VALUE_LABEL='Bund Freier Bürger (Brunner Partei)'
WHERE SHORTNAME = 'bfb';
UPDATE PARTY
SET VALUE_ID=126,
    VALUE_LABEL='BP - Bayernpartei'
WHERE SHORTNAME = 'bayernpartei';
UPDATE PARTY
SET VALUE_ID=127,
    VALUE_LABEL='Bürgerpartei'
WHERE SHORTNAME = 'buergerp';
UPDATE PARTY
SET VALUE_ID=134,
    VALUE_LABEL='BüSo - Bürgerrechtsbewegung Solidarität'
WHERE SHORTNAME = 'solidaritaet';
UPDATE PARTY
SET VALUE_ID=138,
    VALUE_LABEL='CM - Christliche Mitte'
WHERE SHORTNAME = 'cm';
UPDATE PARTY
SET VALUE_ID=147,
    VALUE_LABEL='Feministische Partei'
WHERE SHORTNAME = 'frauen';
UPDATE PARTY
SET VALUE_ID=149,
    VALUE_LABEL='Die Grauen'
WHERE SHORTNAME = 'graue';
UPDATE PARTY
SET VALUE_ID=151,
    VALUE_LABEL='Die Partei'
WHERE SHORTNAME = 'die_partei';
UPDATE PARTY
SET VALUE_ID=152,
    VALUE_LABEL='Die Violetten Alternativen'
WHERE SHORTNAME = 'die_violetten';
UPDATE PARTY
SET VALUE_ID=156,
    VALUE_LABEL='DKP'
WHERE SHORTNAME = 'deutsche_kommunistische_partei';
UPDATE PARTY
SET VALUE_ID=165,
    VALUE_LABEL='DSU'
WHERE SHORTNAME = 'dsu';
UPDATE PARTY
SET VALUE_ID=168,
    VALUE_LABEL='DVU'
WHERE SHORTNAME = 'dvu';
UPDATE PARTY
SET VALUE_ID=171,
    VALUE_LABEL='Familie - Familien-Partei Deutschlands'
WHERE SHORTNAME = 'familienpartei_deutschlands';
UPDATE PARTY
SET VALUE_ID=176,
    VALUE_LABEL='Das Neue Forum'
WHERE SHORTNAME = 'forum';
UPDATE PARTY
SET VALUE_ID=180,
    VALUE_LABEL='FWD - Freie Wähler Deutschlands'
WHERE SHORTNAME = 'fwd';
UPDATE PARTY
SET VALUE_ID=202,
    VALUE_LABEL='MLPD - Marxistisch-Leninistische Partei Deutschlands'
WHERE SHORTNAME = 'marxistischleninistische_partei_deutschlands';
UPDATE PARTY
SET VALUE_ID=206,
    VALUE_LABEL='NPD'
WHERE SHORTNAME = 'nationaldemokratische_partei_deutschlands';
UPDATE PARTY
SET VALUE_ID=209,
    VALUE_LABEL='ÖDP - Ökologisch-Demokratische Partei'
WHERE SHORTNAME = 'oedp';
UPDATE PARTY
SET VALUE_ID=214,
    VALUE_LABEL='PBC - Partei Bibeltreuer Christen'
WHERE SHORTNAME = 'pbc';
UPDATE PARTY
SET VALUE_ID=215,
    VALUE_LABEL='Piratenpartei Deutschland'
WHERE SHORTNAME = 'piratenpartei_deutschland';
UPDATE PARTY
SET VALUE_ID=219,
    VALUE_LABEL='Pro DM'
WHERE SHORTNAME = 'pro_dm';
UPDATE PARTY
SET VALUE_ID=221,
    VALUE_LABEL='PSG - Partei für soziale Gerechtigkeit'
WHERE SHORTNAME = 'psg';
UPDATE PARTY
SET VALUE_ID=224,
    VALUE_LABEL='Rentnerpartei Deutschlands'
WHERE SHORTNAME = 'rentner';
UPDATE PARTY
SET VALUE_ID=225,
    VALUE_LABEL='Republikaner'
WHERE SHORTNAME = 'rep';
UPDATE PARTY
SET VALUE_ID=226,
    VALUE_LABEL='RRP - Rentnerinnen und Rentner Partei'
WHERE SHORTNAME = 'rrp';
UPDATE PARTY
SET VALUE_ID=228,
    VALUE_LABEL='Schill-Partei'
WHERE SHORTNAME = 'schill';
UPDATE PARTY
SET VALUE_ID=235,
    VALUE_LABEL='Statt-Partei'
WHERE SHORTNAME = 'stattpartei';
UPDATE PARTY
SET VALUE_ID=237,
    VALUE_LABEL='Die Tierschutzpartei'
WHERE SHORTNAME = 'die_tierschutzpartei';
UPDATE PARTY
SET VALUE_ID=256,
    VALUE_LABEL='Zentrum - Deutsche Zentrumspartei'
WHERE SHORTNAME = 'zentrum';
UPDATE PARTY
SET VALUE_ID=322,
    VALUE_LABEL='AfD - Alternative für Deutschland'
WHERE SHORTNAME = 'afd';
UPDATE PARTY
SET VALUE_ID=331,
    VALUE_LABEL='ALFA, Liberal-Konservative Reformer'
WHERE SHORTNAME = 'liberalkonservative_reformer';
UPDATE PARTY
SET VALUE_ID=364,
    VALUE_LABEL='Volt'
WHERE SHORTNAME = 'volt_deutschland';
UPDATE PARTY
SET VALUE_ID=372,
    VALUE_LABEL='die Basis'
WHERE SHORTNAME = 'basisdemokratische_partei_deutschland';
UPDATE PARTY
SET VALUE_ID=801,
    VALUE_LABEL='Andere Partei'
WHERE SHORTNAME = 'uebrige';