OPEN SCHEMA NOAH_JUTZ;

SELECT * FROM LOCATION;
TRUNCATE TABLE LOCATION;
MERGE INTO LOCATION l
USING (
    SELECT d.*, v.VALUE_ID AS STATE_VALUE_ID
    FROM ST_META_BUNDESTAG_DISTRICTS d
    JOIN ST_META_POLITBAROMETER_VALUE_LABELS v
    ON edit_distance(d.STATE_NAME, v.label) < 2
    WHERE d.ERROR_INFO IS NULL AND v.VARIABLE_ID = 'v75'
    ORDER BY d.DISTRICT_ID
    ) AS d
ON l.VOTING_DISTRICT_ID = d.DISTRICT_ID
WHEN MATCHED THEN
    UPDATE
    SET l.voting_district_name = d.DISTRICT_NAME,
        l.state_name           = d.STATE_NAME
WHEN NOT MATCHED THEN
    INSERT (VOTING_DISTRICT_ID, VOTING_DISTRICT_NAME, STATE_VALUE_ID, STATE_NAME, IS_WEST_GERMANY)
    VALUES (d.DISTRICT_ID,
            d.DISTRICT_NAME,
            STATE_VALUE_ID,
            d.STATE_NAME,
            CASE
                WHEN d.STATE_NAME IN
                     ('Brandenburg', 'Mecklenburg-Vorpommern', 'Sachsen',
                      'Sachsen-Anhalt', 'Thüringen') THEN FALSE
                WHEN d.STATE_NAME = 'Berlin' AND d.DISTRICT_ID IN (74, 75, 83, 84, 85) THEN FALSE
                ELSE TRUE
                END)

SELECT * FROM ST_META_POLITBAROMETER_VALUE_LABELS
WHERE VARIABLE_ID = 'v75'