OPEN SCHEMA NOAH_JUTZ;

MERGE INTO POLITBAROMETER_ELECTION_POLL t
USING (
    SELECT RESPONDENT_ID,
           STUDY_ID,
           V4A_EAST_WEST,
           V6_INTENDED_VOTE,
           p.SHORTNAME,
           TO_DATE(INTYEAR || '-' || LPAD(INTMONTH, 2, '0'), 'YYYY-MM') AS DATE_MONTH
    FROM ST_POLITBAROMETER_SURVEY
             JOIN PARTY p
                  ON p.VALUE_ID = V6_INTENDED_VOTE
    ) AS s
ON t.RESPONDENT_ID = s.RESPONDENT_ID AND t.RESPONDENT_STUDY_ID = s.STUDY_ID AND
   t.RESPONDENT_EAST_WEST = s.V4A_EAST_WEST AND t.PARTY = s.SHORTNAME
WHEN MATCHED THEN
    UPDATE
    SET t.IS_INTENDED_VOTE = true
WHEN NOT MATCHED THEN
    INSERT
    VALUES (s.DATE_MONTH, RESPONDENT_ID, STUDY_ID, V4A_EAST_WEST, SHORTNAME, TRUE, default, default, default, default)