SELECT * FROM exa_dba_audit_sql WHERE session_id = CURRENT_SESSION;

SELECT CURRENT_STATEMENT;
SELECT CURRENT_USER;
SELECT CURRENT_TIMESTAMP;
SELECT SYSTIMESTAMP;
SELECT CURRENT_SCHEMA;
SELECT CURRENT_SESSION;
SELECT CURRENT_DATE;

SELECT * FROM exa_dba_audit_sql
WHERE session_id = CURRENT_SESSION
ORDER BY stmt_id

SELECT * FROM cat

CLOSE SCHEMA;

CREATE SCHEMA noah;
CREATE TABLE t(i int);
CREATE TABLE "t"(i int);

OPEN SCHEMA NOAH;
SELECT * FROM "t";

DROP SCHEMA  Noah CASCADE;

SELECT * FROM t;

SELECT add_hours(CURRENT_TIMESTAMP, -48);
SELECT to_char(add_days(CURRENT_TIMESTAMP, -2), 'DD');
SELECT to_char(hours_between('2025-03-03', CURRENT_DATE));
SELECT trunc(CURRENT_TIMESTAMP, 'IW');
