OPEN SCHEMA NOAH_JUTZ;

SELECT *
FROM ST_POLITBAROMETER_SURVEY;

-- slicing and dicing

SELECT null as intyear, V8_RATING_SPD as spd, COUNT(*)
FROM ST_POLITBAROMETER_SURVEY
GROUP BY V8_RATING_SPD
union all
SELECT INTYEAR, null as spd, COUNT(*)
FROM ST_POLITBAROMETER_SURVEY
GROUP BY INTYEAR;

-- equivalent

SELECT INTYEAR, V8_RATING_SPD, count(*)
FROM ST_POLITBAROMETER_SURVEY
GROUP BY GROUPING SETS (
    (INTYEAR), ( V8_RATING_SPD) --, (INTYEAR, V8_RATING_SPD), ()
    );

-- multiple groups in a grouping set

SELECT INTYEAR, V8_RATING_SPD, first_value(l.LABEL), count(*)
FROM ST_POLITBAROMETER_SURVEY s
         JOIN ST_META_POLITBAROMETER_VALUE_LABELS l
              ON s.V8_RATING_SPD = l.VALUE_ID
WHERE l.VARIABLE_ID = 'v8'
GROUP BY GROUPING SETS (
    (INTYEAR, V8_RATING_SPD), ()
    )
ORDER BY INTYEAR, V8_RATING_SPD;

-- Rollup

SELECT INTYEAR, V8_RATING_SPD, count(*)
FROM ST_POLITBAROMETER_SURVEY
GROUP BY ROLLUP (
    (INTYEAR, V8_RATING_SPD)
    )
ORDER BY INTYEAR, V8_RATING_SPD;

-- Cube

SELECT INTYEAR, V8_RATING_SPD, count(*)
FROM ST_POLITBAROMETER_SURVEY
GROUP BY CUBE ( INTYEAR, V8_RATING_SPD )
ORDER BY INTYEAR, V8_RATING_SPD;

-- GROUPING

SELECT INTYEAR,
       V8_RATING_SPD,
       GROUPING(INTYEAR),
       GROUPING(V8_RATING_SPD),
       GROUPING(INTYEAR, V8_RATING_SPD), -- binary
       count(*)
FROM ST_POLITBAROMETER_SURVEY
GROUP BY CUBE ( INTYEAR, V8_RATING_SPD )
-- HAVING INTYEAR IS NULL
ORDER BY INTYEAR, V8_RATING_SPD;

-- Window functions: OVER

SELECT DISTINCT INTYEAR, SUM(V8_RATING_SPD) OVER (PARTITION BY INTYEAR)
FROM ST_POLITBAROMETER_SURVEY
ORDER BY INTYEAR;

SELECT V8_RATING_SPD, COUNT(*)
FROM ST_POLITBAROMETER_SURVEY
WHERE INTYEAR = 1990
GROUP BY V8_RATING_SPD