OPEN SCHEMA NOAH_JUTZ;

-- Each distinct combination of the three columns forms a group
SELECT INTMONTH, INTYEAR, V21_POLITICAL_INTEREST_INTENSITY
FROM ST_POLITBAROMETER_SURVEY
GROUP BY 1, 2, 3;

-- Group by month, and group by year by month?
SELECT INTMONTH AS m, INTYEAR AS y, V21_POLITICAL_INTEREST_INTENSITY AS I
FROM ST_POLITBAROMETER_SURVEY
GROUP BY rollup (local.m, local.y, local.I);

-- Window Functions
SELECT DISTINCT INTYEAR, V4A_EAST_WEST, COUNT(*) OVER (PARTITION BY INTYEAR, V4A_EAST_WEST)
FROM ST_POLITBAROMETER_SURVEY
ORDER BY INTYEAR, V4A_EAST_WEST;

-- Cumsum
SELECT INTYEAR,
       V4A_EAST_WEST,
       SUM(V21_POLITICAL_INTEREST_INTENSITY) OVER (PARTITION BY V4A_EAST_WEST ORDER BY RESPONDENT_ID)
FROM ST_POLITBAROMETER_SURVEY
WHERE V21_POLITICAL_INTEREST_INTENSITY > 0
  AND INTYEAR = 2015
ORDER BY INTYEAR, V4A_EAST_WEST;

-- Frame rows
SELECT RESPONDENT_ID,
       V21_POLITICAL_INTEREST_INTENSITY,
       AVG(V21_POLITICAL_INTEREST_INTENSITY)
           OVER (ORDER BY RESPONDENT_ID ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING ) AS av
FROM ST_POLITBAROMETER_SURVEY
WHERE V21_POLITICAL_INTEREST_INTENSITY > 0
  AND INTYEAR = 2015
ORDER BY RESPONDENT_ID;

-- Frame range
SELECT RESPONDENT_ID,
       V21_POLITICAL_INTEREST_INTENSITY,
       AVG(V21_POLITICAL_INTEREST_INTENSITY)
           OVER (ORDER BY RESPONDENT_ID RANGE BETWEEN 2 PRECEDING AND 2 FOLLOWING ) AS av
FROM ST_POLITBAROMETER_SURVEY
WHERE V21_POLITICAL_INTEREST_INTENSITY > 0
  AND INTYEAR = 2015
ORDER BY RESPONDENT_ID;

-- Frame Groups
SELECT RESPONDENT_ID,
       V21_POLITICAL_INTEREST_INTENSITY,
       AVG(V21_POLITICAL_INTEREST_INTENSITY)
           OVER (ORDER BY RESPONDENT_ID GROUPS BETWEEN 2 PRECEDING AND 2 FOLLOWING ) AS av
FROM ST_POLITBAROMETER_SURVEY
WHERE V21_POLITICAL_INTEREST_INTENSITY > 0
  AND INTYEAR = 2015
ORDER BY RESPONDENT_ID;

-- lag/lead
SELECT RESPONDENT_ID,
       V21_POLITICAL_INTEREST_INTENSITY,
       LAG(V21_POLITICAL_INTEREST_INTENSITY)
           OVER (ORDER BY RESPONDENT_ID) AS lg
FROM ST_POLITBAROMETER_SURVEY
WHERE V21_POLITICAL_INTEREST_INTENSITY > 0
  AND INTYEAR = 2015
ORDER BY RESPONDENT_ID;
