OPEN SCHEMA ESCAPEROOM2;

SELECT * FROM TEAMS;

INSERT INTO TEAMS VALUES ('123go');

ALTER USER "NOAH_JUTZ" IDENTIFIED BY "newpassword" REPLACE "NOAH_JUTZ";

OPEN SCHEMA escaperoom2_retail;

SELECT * FROM MARKETS;

SELECT add_days(CURRENT_DATE, -9999);

SELECT * FROM ARTICLE WHERE DESCRIPTION LIKE 'Mamba'; -- 93781

-- todo fix
SELECT TRUNC(S.SALES_TIMESTAMP, 'HH24') AS HOUR_OF_DAY, count(*) AS NUM_SALES
FROM SALES_POSITIONS SP
JOIN SALES S ON S.sales_id=SP.sales_id
WHERE SP.ARTICLE_ID = 93781
AND S.SALES_TIMESTAMP >= TO_DATE('2015-02-12', 'YYYY-MM-DD')
AND S.SALES_TIMESTAMP < TO_DATE('2015-02-13', 'YYYY-MM-DD')
AND TO_DATE(S.SALES_TIMESTAMP) = '2015-02-12'
GROUP BY TRUNC(S.SALES_TIMESTAMP, 'HH24')
ORDER BY HOUR_OF_DAY;

SELECT TRUNC(S.SALES_DATE), SUM(price)
FROM SALES S
JOIN MARKETS M ON M.MARKET_ID = S.MARKET_ID
WHERE M.CITY = 'Hannover'
AND S.SALES_DATE >= TO_DATE('2014-08-01')
AND S.SALES_DATE < TO_DATE('2014-09-01')
GROUP BY TRUNC(S.SALES_DATE);

SELECT TO_CHAR(CURRENT_DATE, 'Day DD. Month');

SELECT PRODUCT_GROUP_DESC, GROUP_CONCAT(DESCRIPTION SEPARATOR ', ') AS ARTICLES
FROM ARTICLE
WHERE BASE_SALES_PRICE < 0.5
GROUP BY PRODUCT_GROUP_DESC;

-- todo fix
SELECT PRODUCT_GROUP_DESC, GROUP_CONCAT((DESCRIPTION || ' (' || BASE_SALES_PRICE || ' EUR)') ORDER BY BASE_SALES_PRICE SEPARATOR ', ') AS ARTICLES
FROM ARTICLE
WHERE BASE_SALES_PRICE < 0.5
GROUP BY PRODUCT_GROUP_DESC
ORDER BY MIN(BASE_SALES_PRICE);

SELECT EAN
FROM ARTICLE
