OPEN SCHEMA NOAH_JUTZ;

CREATE VIEW V_PARTY_YEAR_SUMMARY AS
SELECT
    CAST(EXTRACT(YEAR FROM DATE_MONTH) AS INT) AS vote_year,
    party,
    SUM(CASE WHEN vote_type = 'LAST' THEN 1 ELSE 0 END) AS sum_last_vote,
    SUM(CASE WHEN vote_type = 'INTENDED' THEN 1 ELSE 0 END) AS sum_intended_vote,
    SUM(CASE WHEN vote_type = 'PREFERRED' THEN 1 ELSE 0 END) AS sum_preferred_party
FROM (
    SELECT DATE_MONTH, LAST_VOTE AS party, 'LAST' AS vote_type FROM POLITBAROMETER_SURVEY
    UNION ALL
    SELECT DATE_MONTH, INTENDED_VOTE, 'INTENDED' FROM POLITBAROMETER_SURVEY
    UNION ALL
    SELECT DATE_MONTH, PREFERRED_PARTY, 'PREFERRED' FROM POLITBAROMETER_SURVEY
) unpivoted_votes
WHERE party IS NOT NULL
GROUP BY CAST(EXTRACT(YEAR FROM DATE_MONTH) AS INT), party;