OPEN SCHEMA NOAH_JUTZ;

CREATE OR REPLACE VIEW V_PARTY_YEAR_SUMMARY AS
SELECT CAST(EXTRACT(YEAR FROM DATE_MONTH) AS INT)               AS vote_year,
       state_name,
       party,
       SUM(CASE WHEN vote_type = 'LAST' THEN 1 ELSE 0 END)      AS sum_last_vote,
       SUM(CASE WHEN vote_type = 'INTENDED' THEN 1 ELSE 0 END)  AS sum_intended_vote,
       SUM(CASE WHEN vote_type = 'PREFERRED' THEN 1 ELSE 0 END) AS sum_preferred_party
FROM (
         SELECT s.DATE_MONTH, b.STATE_NAME, s.LAST_VOTE AS party, 'LAST' AS vote_type
         FROM POLITBAROMETER_SURVEY s
                  LEFT JOIN RESPONDENT r ON s.RESPONDENT_ID = r.RESPONDENT_ID
                  LEFT JOIN BUNDESLAND b ON r.BUNDESLAND_ID = b.STATE_VALUE_ID

         UNION ALL

         SELECT s.DATE_MONTH, b.STATE_NAME, s.INTENDED_VOTE, 'INTENDED'
         FROM POLITBAROMETER_SURVEY s
                  LEFT JOIN RESPONDENT r ON s.RESPONDENT_ID = r.RESPONDENT_ID
                  LEFT JOIN BUNDESLAND b ON r.BUNDESLAND_ID = b.STATE_VALUE_ID

         UNION ALL

         SELECT s.DATE_MONTH, b.STATE_NAME, s.PREFERRED_PARTY, 'PREFERRED'
         FROM POLITBAROMETER_SURVEY s
                  LEFT JOIN RESPONDENT r ON s.RESPONDENT_ID = r.RESPONDENT_ID
                  LEFT JOIN BUNDESLAND b ON r.BUNDESLAND_ID = b.STATE_VALUE_ID
         ) unpivoted_votes
WHERE party IS NOT NULL
GROUP BY CAST(EXTRACT(YEAR FROM DATE_MONTH) AS INT), state_name, party;