OPEN SCHEMA NOAH_JUTZ;

CREATE OR REPLACE VIEW V_RESPONDENT_LABELS AS
SELECT
    r.RESPONDENT_ID,
    l_ew.LABEL AS EAST_WEST,
    l_bl.LABEL AS BUNDESLAND,
    l_fs.LABEL AS FINANCIAL_STANDING,
    l_fsf.LABEL AS FINANCIAL_STANDING_FORECAST,
    l_rel.LABEL AS RELIGION,
    l_gen.LABEL AS GENDER,
    l_age.LABEL AS AGE,
    l_mar.LABEL AS MARITAL_STATUS,
    l_edu.LABEL AS EDUCATION,
    l_emp.LABEL AS EMPLOYMENT_STATUS,
    l_occ.LABEL AS OCCUPATION,
    l_uni.LABEL AS WORKERS_UNION
FROM
    RESPONDENT r
-- Join for each demographic column using its specific Variable ID
LEFT JOIN POLITBAROMETER_VALUE_LABELS l_ew
    ON r.EAST_WEST = l_ew.VALUE_ID AND l_ew.VARIABLE_ID = 'v4a'
LEFT JOIN POLITBAROMETER_VALUE_LABELS l_bl
    ON r.BUNDESLAND_ID = l_bl.VALUE_ID AND l_bl.VARIABLE_ID = 'v75'
LEFT JOIN POLITBAROMETER_VALUE_LABELS l_fs
    ON r.FINANCIAL_STANDING = l_fs.VALUE_ID AND l_fs.VARIABLE_ID = 'v27'
LEFT JOIN POLITBAROMETER_VALUE_LABELS l_fsf
    ON r.FINANCIAL_STANDING_FORECAST = l_fsf.VALUE_ID AND l_fsf.VARIABLE_ID = 'v28'
LEFT JOIN POLITBAROMETER_VALUE_LABELS l_rel
    ON r.RELIGION = l_rel.VALUE_ID AND l_rel.VARIABLE_ID = 'v52'
LEFT JOIN POLITBAROMETER_VALUE_LABELS l_gen
    ON r.GENDER = l_gen.VALUE_ID AND l_gen.VARIABLE_ID = 'v54'
LEFT JOIN POLITBAROMETER_VALUE_LABELS l_age
    ON r.AGE = l_age.VALUE_ID AND l_age.VARIABLE_ID = 'v55'
LEFT JOIN POLITBAROMETER_VALUE_LABELS l_mar
    ON r.MARITAL_STATUS = l_mar.VALUE_ID AND l_mar.VARIABLE_ID = 'v57'
LEFT JOIN POLITBAROMETER_VALUE_LABELS l_edu
    ON r.EDUCATION = l_edu.VALUE_ID AND l_edu.VARIABLE_ID = 'v60'
LEFT JOIN POLITBAROMETER_VALUE_LABELS l_emp
    ON r.EMPLOYMENT_STATUS = l_emp.VALUE_ID AND l_emp.VARIABLE_ID = 'v64'
LEFT JOIN POLITBAROMETER_VALUE_LABELS l_occ
    ON r.OCCUPATION = l_occ.VALUE_ID AND l_occ.VARIABLE_ID = 'v65'
LEFT JOIN POLITBAROMETER_VALUE_LABELS l_uni
    ON r.WORKERS_UNION = l_uni.VALUE_ID AND l_uni.VARIABLE_ID = 'v74';