OPEN SCHEMA NOAH_JUTZ;

CREATE OR REPLACE VIEW v_respondent_age_explosion AS
SELECT
    r.RESPONDENT_ID,
    r.MIN_AGE + c.Num - 1 AS Age
FROM RESPONDENT r
JOIN (
    SELECT LEVEL AS Num
    FROM DUAL
    CONNECT BY LEVEL <= 150
) c ON c.Num <= (r.MAX_AGE - r.MIN_AGE + 1)
WHERE r.MIN_AGE IS NOT NULL
  AND r.MAX_AGE IS NOT NULL;