OPEN SCHEMA NOAH_JUTZ;

CREATE OR REPLACE VIEW v_turnout_by_state_district AS
WITH Turnout AS (
    SELECT CASE
               WHEN GROUPING(c.TERM) = 0 AND GROUPING(s.STATE_NAME) = 0 AND GROUPING(d.VOTING_DISTRICT_NAME) = 0 THEN 'District Level'
               WHEN GROUPING(c.TERM) = 0 AND GROUPING(s.STATE_NAME) = 0 THEN 'State Level'
               WHEN GROUPING(c.TERM) = 0 THEN 'Term Level'
               ELSE 'Grand Total'
           END AS GROUP_LEVEL,
           c.TERM,
           s.STATE_NAME,
           d.VOTING_DISTRICT_NAME,
           SUM(c.VOTERS) / SUM(c.VOTING_ELIGIBLE_POPULATION) * 100 AS TURNOUT_PERCENTAGE
    FROM BUNDESTAG_ELECTION_CENSUS c
    JOIN VOTING_DISTRICT d ON c.DISTRICT_ID = d.VOTING_DISTRICT_ID
    JOIN BUNDESLAND s ON d.STATE_ID = s.STATE_VALUE_ID
    GROUP BY ROLLUP (c.TERM, s.STATE_NAME, d.VOTING_DISTRICT_NAME)
),
TopParty AS (
    SELECT TERM, STATE_NAME, VOTING_DISTRICT_NAME, PARTY
    FROM (
        SELECT r.TERM, s.STATE_NAME, d.VOTING_DISTRICT_NAME, r.PARTY,
               ROW_NUMBER() OVER (
                   PARTITION BY r.TERM, s.STATE_NAME, d.VOTING_DISTRICT_NAME
                   ORDER BY SUM(r.VOTES) DESC
               ) as rnk
        FROM BUNDESTAG_ELECTION_RESULT r
        JOIN VOTING_DISTRICT d ON r.DISTRICT_ID = d.VOTING_DISTRICT_ID
        JOIN BUNDESLAND s ON d.STATE_ID = s.STATE_VALUE_ID
        GROUP BY r.PARTY, ROLLUP(r.TERM, s.STATE_NAME, d.VOTING_DISTRICT_NAME)
    ) ranked
    WHERE rnk = 1
)
SELECT
    t.GROUP_LEVEL,
    t.TERM,
    t.STATE_NAME,
    t.VOTING_DISTRICT_NAME,
    t.TURNOUT_PERCENTAGE,
    p.PARTY AS MOST_POPULAR_PARTY
FROM Turnout t
LEFT JOIN TopParty p
  ON (t.TERM = p.TERM OR (t.TERM IS NULL AND p.TERM IS NULL))
 AND (t.STATE_NAME = p.STATE_NAME OR (t.STATE_NAME IS NULL AND p.STATE_NAME IS NULL))
 AND (t.VOTING_DISTRICT_NAME = p.VOTING_DISTRICT_NAME OR (t.VOTING_DISTRICT_NAME IS NULL AND p.VOTING_DISTRICT_NAME IS NULL))
ORDER BY t.TERM, t.STATE_NAME, t.VOTING_DISTRICT_NAME;