OPEN SCHEMA NOAH_JUTZ;

-- Check for answer options that aren't mapped identically

SELECT c.LABEL, v.LABEL, v.VALUE_ID
FROM ST_META_POLITBAROMETER_VALUE_LABELS v
JOIN ST_META_POLITBAROMETER_COLUMN_LABELS c
ON v.VARIABLE_ID = c.VARIABLE_ID
WHERE v.LABEL IN (SELECT LABEL
                FROM ST_META_POLITBAROMETER_VALUE_LABELS
                GROUP BY LABEL
                HAVING COUNT(DISTINCT VALUE_ID) > 1)


