OPEN SCHEMA NOAH_JUTZ;

-- PowerBI needs single PK/FKs.

SELECT MIN(RESPONDENT_ID), MAX(RESPONDENT_ID) FROM ST_POLITBAROMETER_SURVEY;
SELECT (V4A_EAST_WEST, COUNT(V4A_EAST_WEST)) FROM ST_POLITBAROMETER_SURVEY GROUP BY V4A_EAST_WEST;
SELECT MIN(RESPONDENT_ID), MAX(STUDY_ID) FROM ST_POLITBAROMETER_SURVEY;

-- NEW_RESPONDENT_ID := (RESPONDENT_ID * 10000000) + (V4A_EAST_WEST * 1000000) + STUDY_ID

-- Add color to party

ALTER TABLE PARTY ADD COLUMN HEX_COLOR CHAR(7);
-- Established and recognizable parties with assigned colors
UPDATE PARTY SET HEX_COLOR = '32302E' WHERE SHORTNAME = 'iiiweg';
UPDATE PARTY SET HEX_COLOR = '005A9C' WHERE SHORTNAME = 'ssw';
UPDATE PARTY SET HEX_COLOR = '002D62' WHERE SHORTNAME = 'drp';
UPDATE PARTY SET HEX_COLOR = '002244' WHERE SHORTNAME = 'offensive_d';
UPDATE PARTY SET HEX_COLOR = 'FF8800' WHERE SHORTNAME = 'piratenpartei_deutschland';
UPDATE PARTY SET HEX_COLOR = 'DF0000' WHERE SHORTNAME = 'marxistischleninistische_partei_deutschlands';
UPDATE PARTY SET HEX_COLOR = '46962B' WHERE SHORTNAME = 'gruene';
UPDATE PARTY SET HEX_COLOR = 'E3000F' WHERE SHORTNAME = 'kpd';
UPDATE PARTY SET HEX_COLOR = '501050' WHERE SHORTNAME = 'volt_deutschland';
UPDATE PARTY SET HEX_COLOR = 'F29400' WHERE SHORTNAME = 'freiewaehler';
UPDATE PARTY SET HEX_COLOR = '4A90E2' WHERE SHORTNAME = 'die_tierschutzpartei';
UPDATE PARTY SET HEX_COLOR = '000000' WHERE SHORTNAME = 'die_partei';
UPDATE PARTY SET HEX_COLOR = '8B0000' WHERE SHORTNAME = 'rep';
UPDATE PARTY SET HEX_COLOR = '009EE0' WHERE SHORTNAME = 'afd';
UPDATE PARTY SET HEX_COLOR = '4A4A4A' WHERE SHORTNAME = 'nationaldemokratische_partei_deutschlands';
UPDATE PARTY SET HEX_COLOR = '000000' WHERE SHORTNAME = 'union';
UPDATE PARTY SET HEX_COLOR = '1A2B3C' WHERE SHORTNAME = 'team_todenhoefer';
UPDATE PARTY SET HEX_COLOR = '004B49' WHERE SHORTNAME = 'basisdemokratische_partei_deutschland';
UPDATE PARTY SET HEX_COLOR = '0A3370' WHERE SHORTNAME = 'liberalkonservative_reformer';
UPDATE PARTY SET HEX_COLOR = 'BE3075' WHERE SHORTNAME = 'linke';
UPDATE PARTY SET HEX_COLOR = 'E3A000' WHERE SHORTNAME = 'oedp';
UPDATE PARTY SET HEX_COLOR = 'FFED00' WHERE SHORTNAME = 'fdp';
UPDATE PARTY SET HEX_COLOR = 'FF007F' WHERE SHORTNAME = 'buendnis_grundeinkommen';
UPDATE PARTY SET HEX_COLOR = 'E3000F' WHERE SHORTNAME = 'spd';
UPDATE PARTY SET HEX_COLOR = '008AC5' WHERE SHORTNAME = 'bayernpartei';
UPDATE PARTY SET HEX_COLOR = 'A62626' WHERE SHORTNAME = 'dvu';
UPDATE PARTY SET HEX_COLOR = 'E3000F' WHERE SHORTNAME = 'deutsche_kommunistische_partei';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'uebrige';

-- Additional historical/discernible party colors
UPDATE PARTY SET HEX_COLOR = '4A4A4A' WHERE SHORTNAME = 'dierechte'; -- Right-Wing Grey
UPDATE PARTY SET HEX_COLOR = 'FFCC00' WHERE SHORTNAME = 'schill'; -- Law & Order Yellow/Orange
UPDATE PARTY SET HEX_COLOR = '0080FF' WHERE SHORTNAME = 'stattpartei'; -- Soft Blue
UPDATE PARTY SET HEX_COLOR = 'A62626' WHERE SHORTNAME = 'fap'; -- Far-Right Dark Red
UPDATE PARTY SET HEX_COLOR = '4B2C5C' WHERE SHORTNAME = 'die_violetten'; -- Violet
UPDATE PARTY SET HEX_COLOR = 'FF6600' WHERE SHORTNAME = 'buergerbewegung'; -- Pro-NRW/Bürgerbewegung Orange
UPDATE PARTY SET HEX_COLOR = '000080' WHERE SHORTNAME = 'zentrum'; -- Traditional Catholic Center Navy Blue
UPDATE PARTY SET HEX_COLOR = 'D4AF37' WHERE SHORTNAME = 'deutsche_mitte'; -- Gold/Ocher
UPDATE PARTY SET HEX_COLOR = '1A1A1A' WHERE SHORTNAME = 'appd'; -- Anarchist Black
UPDATE PARTY SET HEX_COLOR = 'E3000F' WHERE SHORTNAME = 'dkpdrp'; -- Communist Alliance Red
UPDATE PARTY SET HEX_COLOR = 'E3000F' WHERE SHORTNAME = 'psg'; -- Socialist Equality Red
UPDATE PARTY SET HEX_COLOR = '46962B' WHERE SHORTNAME = 'oekounion'; -- Eco-Green
UPDATE PARTY SET HEX_COLOR = 'F5A623' WHERE SHORTNAME = 'familienpartei_deutschlands'; -- Family Orange
UPDATE PARTY SET HEX_COLOR = '005A9C' WHERE SHORTNAME = 'dsu'; -- Regional Conservative Blue

-- All remaining uncoded/niche parties set to fallback 'uebrige' color (999999)
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'mieterpartei';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'apd';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'dvp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'aufbruch';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'dmp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'buendnis21';
piUPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'rsf';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'bwk';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'avp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'partei_der_humanisten';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'fwd';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'solidaritaet';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'buendnis_c';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'demokraten';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'ab2000';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'du';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'gpd';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'fu';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = '5block';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'cm';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'rfp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'graue';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'cvp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'adm';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'humanwirtschafts_partei';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'wgnd';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'fsu';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'evd';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'freie_union';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'volksabstimmung';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'vu';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'gdp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'gartenpartei';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'usd';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'big';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'wav';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'ab_jetztdemokratie_durch_volksabstimmung';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'aud';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'dfu';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'deutschland';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'neue_liberale_die_sozialliberalen';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'muendige';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'chance2000';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'ep';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'die_urbane_eine_hiphop_partei';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'frauen';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'dg';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'forum';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'shlp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'dns';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'fdv';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'dp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = '50plus';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'hp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'patrioten';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'bsa';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'spad';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'bfb';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'ddd';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'lfk';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'partei_des_fortschritts';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'pass';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'rentner';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'pro_deutschland';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'nein';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'dpd';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'pbc';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'naturgesetz';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'magdeburger_gartenpartei';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'dfp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'menschliche_welt';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'uap';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'gbbhe';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'allianz_fuer_menschenrechte_tier_und_naturschutz';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'gvp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'pro_dm';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'kbw';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'asd';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'liga';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'mittelstand';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'rrp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'adf';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'efp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'eap';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'allianz_deutscher_demokraten';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'verjuengungsforschung';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'vl';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'dv';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'bgd';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'liebe';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'cbv';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'partei_der_vernunft';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'prg';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'vaa';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'buergerp';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'graue_panther';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'gim';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'pdgd';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'demokratieinbewegung';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'fbu';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'ld';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'v';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'b';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'agfg';
UPDATE PARTY SET HEX_COLOR = '999999' WHERE SHORTNAME = 'bdd';

UPDATE PARTY SET HEX_COLOR = '#' || HEX_COLOR;