OPEN SCHEMA NOAH_JUTZ;

-- PowerBI needs single PK/FKs.

SELECT MIN(RESPONDENT_ID), MAX(RESPONDENT_ID) FROM ST_POLITBAROMETER_SURVEY;
SELECT (V4A_EAST_WEST, COUNT(V4A_EAST_WEST)) FROM ST_POLITBAROMETER_SURVEY GROUP BY V4A_EAST_WEST;
SELECT MIN(RESPONDENT_ID), MAX(STUDY_ID) FROM ST_POLITBAROMETER_SURVEY;

-- NEW_RESPONDENT_ID := (RESPONDENT_ID * 10000000) + (V4A_EAST_WEST * 1000000) + STUDY_ID