OPEN SCHEMA NOAH_JUTZ;

-- Check strange patterns in visualizations

-- Age only exists from 1977-1989
SELECT AGE, COUNT(*)
FROM RESPONDENT r
JOIN POLITBAROMETER_SURVEY s
ON s.RESPONDENT_ID = r.RESPONDENT_ID
WHERE s.DATE_MONTH > '1989-01-01'
GROUP BY AGE;