OPEN SCHEMA NOAH_JUTZ;

-- Check strange patterns in visualizations

-- Age only exists from 1977-1989
SELECT AGE, COUNT(*)
FROM RESPONDENT r
JOIN POLITBAROMETER_SURVEY s
ON s.RESPONDENT_ID = r.RESPONDENT_ID
WHERE s.DATE_MONTH > '1989-01-01'
GROUP BY AGE;

-- Check after schema change

SELECT COUNT(*)
FROM RESPONDENT
WHERE MIN_AGE != MAX_AGE; -- 0

SELECT V56_AGE_GROUP, COUNT(*)
FROM ST_POLITBAROMETER_SURVEY
GROUP BY V56_AGE_GROUP; -- 0

-- => staging area has no age data on v56