OPEN SCHEMA NOAH_JUTZ;

-- Check for missing parties

SELECT E.PARTY, COUNT(*) AS cnt
FROM ST_BUNDESTAG_ELECTIONS E
         FULL OUTER JOIN ST_META_BUNDESTAG_PARTIES P
                         ON E.PARTY = P.SHORTNAME
WHERE P.SHORTNAME IS NULL
GROUP BY E.PARTY
ORDER BY cnt desc;

-- Add missing parties

INSERT INTO ST_META_BUNDESTAG_PARTIES
SELECT DISTINCT E.PARTY, NULL
FROM ST_BUNDESTAG_ELECTIONS E
         LEFT JOIN ST_META_BUNDESTAG_PARTIES P ON E.PARTY = P.SHORTNAME
WHERE P.SHORTNAME IS NULL;