OPEN SCHEMA NOAH_JUTZ;

-- Check if district_id 1..1 district_name
SELECT DISTINCT DISTRICT_ID, COUNT(DISTINCT DISTRICT_NAME)
FROM ST_BUNDESTAG_ELECTIONS
GROUP BY DISTRICT_ID
ORDER BY DISTRICT_ID;

-- Cross-check with st_Meta_Bundestag_Parties
SELECT e.PARTY, l.SHORTNAME
FROM ST_BUNDESTAG_ELECTIONS e
         LEFT JOIN ST_META_BUNDESTAG_PARTIES l
                   ON l.SHORTNAME = e.PARTY
WHERE e.PARTY != l.SHORTNAME;