OPEN SCHEMA NOAH_JUTZ;

-- 1D Skyline: All rows with the highest government rating

SELECT DATE_MONTH, RATING_GOVERNMENT
FROM POLITBAROMETER_SURVEY
WHERE RATING_GOVERNMENT IS NOT NULL
    PREFERRING HIGH RATING_GOVERNMENT
ORDER BY RATING_GOVERNMENT, DATE_MONTH DESC
LIMIT 10;

-- In which districts was voter turnout high with many invalid votes?

SELECT C.TERM,
       D.VOTING_DISTRICT_NAME,
       (C.VOTERS / C.VOTING_ELIGIBLE_POPULATION) AS TURNOUT,
       (C.INVALID_VOTES / C.VOTERS)              AS INVALID_RATE
FROM BUNDESTAG_ELECTION_CENSUS C
         JOIN VOTING_DISTRICT D ON C.DISTRICT_ID = D.VOTING_DISTRICT_ID
WHERE C.VOTERS > 0
    PREFERRING HIGH (C.VOTERS / C.VOTING_ELIGIBLE_POPULATION) PLUS HIGH (C.INVALID_VOTES / C.VOTERS)
ORDER BY TERM DESC, INVALID_RATE DESC;
