OPEN SCHEMA NOAH_JUTZ;

-- How correlated are personal financial standing and government approval in each state?

SELECT
    b.STATE_NAME,
    CORR(ps.RATING_GOVERNMENT, 6 - r.FINANCIAL_STANDING_FORECAST) AS CORRELATION_COEFF,
    COVAR_POP(ps.RATING_GOVERNMENT, 6 - r.FINANCIAL_STANDING_FORECAST) AS COVARIANCE_POP,
    COUNT(*) AS SAMPLE_SIZE
FROM POLITBAROMETER_SURVEY ps
JOIN RESPONDENT r
    ON ps.RESPONDENT_ID = r.RESPONDENT_ID
   AND ps.RESPONDENT_STUDY_ID = r.STUDY_ID
   AND ps.RESPONDENT_EAST_WEST = r.EAST_WEST
JOIN BUNDESLAND b
    ON r.BUNDESLAND_ID = b.STATE_VALUE_ID
GROUP BY b.STATE_NAME;