OPEN SCHEMA NOAH_JUTZ;

-- How does each party's rating change month over month?

SELECT PARTY,
       DATE_MONTH,
       SUM(RATING * WEIGHT) / SUM(WEIGHT)                                                       AS CURRENT_AVG_RATING,
       LAG(SUM(RATING * WEIGHT) / SUM(WEIGHT), 1) OVER (PARTITION BY PARTY ORDER BY DATE_MONTH) AS PREVIOUS_MONTH_AVG,
       SUM(RATING * WEIGHT) / SUM(WEIGHT) -
       LAG(SUM(RATING * WEIGHT) / SUM(WEIGHT), 1) OVER (PARTITION BY PARTY ORDER BY DATE_MONTH) AS SENTIMENT_DELTA
FROM POLITBAROMETER_PARTY_RATINGS
WHERE WEIGHT > 0
GROUP BY PARTY, DATE_MONTH
ORDER BY DATE_MONTH;
