OPEN SCHEMA NOAH_JUTZ;

MERGE INTO SEAT_DISTRIBUTION t
USING (
    SELECT 'union' AS PARTY, (cdu + csu) AS seats, TO_DATE(TO_CHAR(INTYEAR), 'YYYY') AS DATE_YEAR
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'afd', afd, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'spd', spd, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'gruene', gruene, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'linke', linke, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'ssw', ssw, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'fdp', fdp, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'bayernpartei', bp, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'dp', dp, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'deutsche_kommunistische_partei', kpd, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'wav', wav, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'zentrum', zentrum, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'dkpdrp', dkpdrp, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'gbbhe', gbbhe, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'fdv', fdv, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    UNION ALL
    SELECT 'uebrige', independent, TO_DATE(TO_CHAR(INTYEAR), 'YYYY')
    FROM ST_SEAT_DISTRIBUTION
    ) AS s
ON t.PARTY = s.PARTY AND t.TERM = s.DATE_YEAR
WHEN MATCHED THEN
    UPDATE
    SET t.SEATS = s.SEATS
WHEN NOT MATCHED THEN
    INSERT
    VALUES (s.DATE_YEAR, s.PARTY, s.SEATS);