OPEN SCHEMA NOAH_JUTZ;

MERGE INTO POLITBAROMETER_SURVEY t
USING (
    SELECT s.RESPONDENT_ID,
           s.INTYEAR,
           s.INTMONTH,
           s.STUDY_ID,
           s.VERSION,
           s.D_WEIGHT,
           s.V4A_EAST_WEST,
           CASE WHEN s.V5_TURNOUT >= 0 THEN s.V5_TURNOUT END                         AS V5_TURNOUT,
           CASE WHEN s.V6_INTENDED_VOTE >= 0 THEN s.V6_INTENDED_VOTE END             AS V6_INTENDED_VOTE,
           CASE WHEN s.V7_LAST_VOTE >= 0 THEN s.V7_LAST_VOTE END                     AS V7_LAST_VOTE,
           CASE WHEN s.V8_RATING_SPD >= 0 THEN s.V8_RATING_SPD END                   AS V8_RATING_SPD,
           CASE WHEN s.V9_RATING_CDU >= 0 THEN s.V9_RATING_CDU END                   AS V9_RATING_CDU,
           CASE WHEN s.V10_RATING_CSU >= 0 THEN s.V10_RATING_CSU END                 AS V10_RATING_CSU,
           CASE WHEN s.V11_RATING_FDP >= 0 THEN s.V11_RATING_FDP END                 AS V11_RATING_FDP,
           CASE WHEN s.V12_RATING_GRUENE >= 0 THEN s.V12_RATING_GRUENE END           AS V12_RATING_GRUENE,
           CASE WHEN s.V13_RATING_AFD >= 0 THEN s.V13_RATING_AFD END                 AS V13_RATING_AFD,
           CASE WHEN s.V14_RATING_LINKE >= 0 THEN s.V14_RATING_LINKE END             AS V14_RATING_LINKE,
           CASE WHEN s.V15_RATING_GOVERNMENT >= 0 THEN s.V15_RATING_GOVERNMENT END   AS V15_RATING_GOVERNMENT,
           CASE WHEN s.V16_RATING_OPPOSITION >= 0 THEN s.V16_RATING_OPPOSITION END   AS V16_RATING_OPPOSITION,
           CASE
               WHEN s.V18_DEMOCRACY_SATISFACTION >= 0
                   THEN s.V18_DEMOCRACY_SATISFACTION END                             AS V18_DEMOCRACY_SATISFACTION,
           CASE
               WHEN s.V21_POLITICAL_INTEREST_INTENSITY >= 0
                   THEN s.V21_POLITICAL_INTEREST_INTENSITY END                       AS V21_POLITICAL_INTEREST_INTENSITY,
           CASE WHEN s.V22_LEFT_RIGHT >= 0 THEN s.V22_LEFT_RIGHT END                 AS V22_LEFT_RIGHT,
           CASE WHEN s.V25_ECONOMY_BRD >= 0 THEN s.V25_ECONOMY_BRD END               AS V25_ECONOMY_BRD,
           CASE WHEN s.V26_ECONOMY_FORECAST >= 0 THEN s.V26_ECONOMY_FORECAST END     AS V26_ECONOMY_FORECAST,
           CASE WHEN s.V27_FINANCIAL_STANDING >= 0 THEN s.V27_FINANCIAL_STANDING END AS V27_FINANCIAL_STANDING,
           CASE
               WHEN s.V28_FINANCIAL_STANDING_FORECAST >= 0
                   THEN s.V28_FINANCIAL_STANDING_FORECAST END                        AS V28_FINANCIAL_STANDING_FORECAST,
           CASE WHEN s.V29_REUNIFICATION >= 0 THEN s.V29_REUNIFICATION END           AS V29_REUNIFICATION,
           CASE WHEN s.V30_ASYLUM >= 0 THEN s.V30_ASYLUM END                         AS V30_ASYLUM,
           CASE WHEN s.V41_CRIME_THREAT >= 0 THEN s.V41_CRIME_THREAT END             AS V41_CRIME_THREAT,
           CASE WHEN s.V42_EU_MEMBERSHIP >= 0 THEN s.V42_EU_MEMBERSHIP END           AS V42_EU_MEMBERSHIP,
           CASE WHEN s.V44_SOCIETY >= 0 THEN s.V44_SOCIETY END                       AS V44_SOCIETY,
           CASE WHEN s.V50_YEAR_REVIEW >= 0 THEN s.V50_YEAR_REVIEW END               AS V50_YEAR_REVIEW,
           CASE WHEN s.V51_YEAR_FORECAST >= 0 THEN s.V51_YEAR_FORECAST END           AS V51_YEAR_FORECAST,
           CASE WHEN s.V52_RELIGION >= 0 THEN s.V52_RELIGION END                     AS V52_RELIGION,
           CASE WHEN s.V54_GENDER >= 0 THEN s.V54_GENDER END                         AS V54_GENDER,
           CASE WHEN s.V55_AGE >= 0 THEN s.V55_AGE END                               AS V55_AGE,
           CASE WHEN s.V57_MARITAL_STATUS >= 0 THEN s.V57_MARITAL_STATUS END         AS V57_MARITAL_STATUS,
           CASE WHEN s.V59_EDUCATION_PRE_87 >= 0 THEN s.V59_EDUCATION_PRE_87 END     AS V59_EDUCATION_PRE_87,
           CASE WHEN s.V60_EDUCATION >= 0 THEN s.V60_EDUCATION END                   AS V60_EDUCATION,
           CASE WHEN s.V64_EMPLOYMENT_STATUS >= 0 THEN s.V64_EMPLOYMENT_STATUS END   AS V64_EMPLOYMENT_STATUS,
           CASE WHEN s.V65_OCCUPATION >= 0 THEN s.V65_OCCUPATION END                 AS V65_OCCUPATION,
           CASE WHEN s.V72_PREFERRED_PARTY >= 0 THEN s.V72_PREFERRED_PARTY END       AS V72_PREFERRED_PARTY,
           CASE
               WHEN s.V73_PREFERENCE_INTENSITY >= 0
                   THEN s.V73_PREFERENCE_INTENSITY END                               AS V73_PREFERENCE_INTENSITY,
           CASE WHEN s.V74_WORKERS_UNION >= 0 THEN s.V74_WORKERS_UNION END           AS V74_WORKERS_UNION,
           CASE WHEN s.V75_STATE >= 0 THEN s.V75_STATE END                           AS V75_STATE,
           p_v6.SHORTNAME                                                            AS intended_vote,
           p_v7.SHORTNAME                                                            AS last_vote,
           p_v72.SHORTNAME                                                           AS preferred
    FROM ST_POLITBAROMETER_SURVEY s
             LEFT JOIN MAPPING_PARTY_POLITBAROMETER_VALUE_LABELS p_v6
                       ON p_v6.VALUE_ID = s.V6_INTENDED_VOTE
             LEFT JOIN MAPPING_PARTY_POLITBAROMETER_VALUE_LABELS p_v7
                       ON p_v7.VALUE_ID = s.V7_LAST_VOTE
             LEFT JOIN MAPPING_PARTY_POLITBAROMETER_VALUE_LABELS p_v72
                       ON p_v72.VALUE_ID = s.V72_PREFERRED_PARTY
    QUALIFY ROW_NUMBER() OVER (PARTITION BY RESPONDENT_ID, STUDY_ID, V4A_EAST_WEST) = 1
    ) AS s
ON s.RESPONDENT_ID = t.RESPONDENT_ID AND s.V4A_EAST_WEST = t.RESPONDENT_EAST_WEST AND s.STUDY_ID = t.RESPONDENT_STUDY_ID
WHEN MATCHED THEN
    UPDATE
    SET t.DATE_MONTH             = TO_DATE(INTYEAR || '-' || LPAD(INTMONTH, 2, '0'), 'YYYY-MM'),
        t.WEIGHT                 = s.D_WEIGHT,
        t.TURNOUT                = s.V5_TURNOUT,
        t.RATING_GOVERNMENT      = s.V15_RATING_GOVERNMENT,
        t.RATING_OPPOSITION      = s.V16_RATING_OPPOSITION,
        t.DEMOCRACY_SATISFACTION = s.V18_DEMOCRACY_SATISFACTION,
        t.POLITICAL_INTEREST     = s.V21_POLITICAL_INTEREST_INTENSITY,
        t.LEFT_RIGHT             = s.V22_LEFT_RIGHT,
        t.ECONOMY_CURRENT        = s.V25_ECONOMY_BRD,
        t.ECONOMY_FORECAST       = s.V26_ECONOMY_FORECAST,
        t.REUNIFICATION          = s.V29_REUNIFICATION,
        t.ASYLUM                 = s.V30_ASYLUM,
        t.CRIME_THREAT           = s.V41_CRIME_THREAT,
        t.EU_MEMBERSHIP          = s.V42_EU_MEMBERSHIP,
        t.SOCIETY                = s.V44_SOCIETY,
        t.YEAR_REVIEW            = s.V50_YEAR_REVIEW,
        t.YEAR_FORECAST          = s.V51_YEAR_FORECAST,
        t.INTENDED_VOTE          = s.INTENDED_VOTE,
        t.LAST_VOTE              = s.LAST_VOTE,
        t.PREFERRED_PARTY        = s.PREFERRED,
        t.PREFERENCE_INTENSITY   = s.V73_PREFERENCE_INTENSITY
WHEN NOT MATCHED THEN
    INSERT
    VALUES (s.RESPONDENT_ID,
            s.STUDY_ID,
            s.V4A_EAST_WEST,
            TO_DATE(INTYEAR || '-' || LPAD(INTMONTH, 2, '0'), 'YYYY-MM'),
            s.D_WEIGHT,
            s.V5_TURNOUT,
            s.V15_RATING_GOVERNMENT,
            s.V16_RATING_OPPOSITION,
            s.V18_DEMOCRACY_SATISFACTION,
            s.V21_POLITICAL_INTEREST_INTENSITY,
            s.V22_LEFT_RIGHT,
            s.V25_ECONOMY_BRD,
            s.V26_ECONOMY_FORECAST,
            s.V29_REUNIFICATION,
            s.V30_ASYLUM,
            s.V41_CRIME_THREAT,
            s.V42_EU_MEMBERSHIP,
            s.V44_SOCIETY,
            s.V50_YEAR_REVIEW,
            s.V51_YEAR_FORECAST,
            s.INTENDED_VOTE,
            s.LAST_VOTE,
            s.PREFERRED,
            s.V73_PREFERENCE_INTENSITY);

