OPEN SCHEMA NOAH_JUTZ;

MERGE INTO POLITBAROMETER_VALUE_LABELS t
USING ST_META_POLITBAROMETER_VALUE_LABELS s
ON t.VALUE_ID = s.VALUE_ID AND t.VARIABLE_ID = s.VARIABLE_ID
WHEN MATCHED THEN UPDATE SET t.LABEL = s.LABEL
WHEN NOT MATCHED THEN INSERT VALUES (VARIABLE_ID, VALUE_ID, LABEL);