OPEN SCHEMA NOAH_JUTZ;

MERGE INTO POLITBAROMETER_SURVEY t
USING (
    SELECT s.*, p_v6.SHORTNAME AS intended_vote, p_v7.SHORTNAME as last_vote, p_v72.SHORTNAME as preferred
    FROM ST_POLITBAROMETER_SURVEY s
             LEFT JOIN MAPPING_PARTY_POLITBAROMETER_VALUE_LABELS p_v6
                       ON p_v6.VALUE_ID = s.V6_INTENDED_VOTE
             LEFT JOIN MAPPING_PARTY_POLITBAROMETER_VALUE_LABELS p_v7
                       ON p_v7.VALUE_ID = s.V7_LAST_VOTE
             LEFT JOIN MAPPING_PARTY_POLITBAROMETER_VALUE_LABELS p_v72
                       ON p_v72.VALUE_ID = s.V72_PREFERRED_PARTY
    QUALIFY ROW_NUMBER() OVER (PARTITION BY RESPONDENT_ID, STUDY_ID, V4A_EAST_WEST) = 1
    ) AS s
ON s.RESPONDENT_ID = t.RESPONDENT_ID AND s.V4A_EAST_WEST = t.RESPONDENT_EAST_WEST AND s.STUDY_ID = t.RESPONDENT_STUDY_ID
WHEN MATCHED THEN
    UPDATE
    SET t.DATE_MONTH             = TO_DATE(INTYEAR || '-' || LPAD(INTMONTH, 2, '0'), 'YYYY-MM'),
        t.WEIGHT                 = s.D_WEIGHT,
        t.TURNOUT                = s.V5_TURNOUT,
        t.RATING_GOVERNMENT      = s.V15_RATING_GOVERNMENT,
        t.RATING_OPPOSITION      = s.V16_RATING_OPPOSITION,
        t.DEMOCRACY_SATISFACTION = s.V18_DEMOCRACY_SATISFACTION,
        t.POLITICAL_INTEREST     = s.V21_POLITICAL_INTEREST_INTENSITY,
        t.LEFT_RIGHT             = s.V22_LEFT_RIGHT,
        t.ECONOMY_CURRENT        = s.V25_ECONOMY_BRD,
        t.ECONOMY_FORECAST       = s.V26_ECONOMY_FORECAST,
        t.REUNIFICATION          = s.V29_REUNIFICATION,
        t.ASYLUM                 = s.V30_ASYLUM,
        t.CRIME_THREAT           = s.V41_CRIME_THREAT,
        t.EU_MEMBERSHIP          = s.V42_EU_MEMBERSHIP,
        t.SOCIETY                = s.V44_SOCIETY,
        t.YEAR_REVIEW            = s.V50_YEAR_REVIEW,
        t.YEAR_FORECAST          = s.V51_YEAR_FORECAST,
        t.INTENDED_VOTE          = s.INTENDED_VOTE,
        t.LAST_VOTE              = s.LAST_VOTE,
        t.PREFERRED_PARTY        = s.PREFERRED,
        t.PREFERENCE_INTENSITY   = s.V73_PREFERENCE_INTENSITY
WHEN NOT MATCHED THEN
    INSERT
    VALUES (s.RESPONDENT_ID,
            s.STUDY_ID,
            s.V4A_EAST_WEST,
            TO_DATE(INTYEAR || '-' || LPAD(INTMONTH, 2, '0'), 'YYYY-MM'),
            s.D_WEIGHT,
            s.V5_TURNOUT,
            s.V15_RATING_GOVERNMENT,
            s.V16_RATING_OPPOSITION,
            s.V18_DEMOCRACY_SATISFACTION,
            s.V21_POLITICAL_INTEREST_INTENSITY,
            s.V22_LEFT_RIGHT,
            s.V25_ECONOMY_BRD,
            s.V26_ECONOMY_FORECAST,
            s.V29_REUNIFICATION,
            s.V30_ASYLUM,
            s.V41_CRIME_THREAT,
            s.V42_EU_MEMBERSHIP,
            s.V44_SOCIETY,
            s.V50_YEAR_REVIEW,
            s.V51_YEAR_FORECAST,
            s.INTENDED_VOTE,
            s.LAST_VOTE,
            s.PREFERRED,
            s.V73_PREFERENCE_INTENSITY);

