OPEN SCHEMA NOAH_JUTZ;

MERGE INTO RESPONDENT t
USING (
    SELECT *
    FROM ST_POLITBAROMETER_SURVEY
    QUALIFY ROW_NUMBER() OVER (PARTITION BY RESPONDENT_ID, STUDY_ID, V4A_EAST_WEST) = 1
    ) AS s
ON t.RESPONDENT_ID = s.RESPONDENT_ID AND t.STUDY_ID = s.STUDY_ID AND t.EAST_WEST = s.V4A_EAST_WEST
WHEN MATCHED THEN
    UPDATE
    SET t.BUNDESLAND_ID               = CASE WHEN V75_STATE < 0 THEN NULL ELSE V75_STATE END,
        t.FINANCIAL_STANDING          = s.V27_FINANCIAL_STANDING,
        t.FINANCIAL_STANDING_FORECAST = s.V28_FINANCIAL_STANDING_FORECAST,
        t.RELIGION                    = s.V52_RELIGION,
        t.GENDER                      = s.V54_GENDER,
        t.AGE                         = s.V55_AGE,
        t.MARITAL_STATUS              = s.V57_MARITAL_STATUS,
        t.EDUCATION                   = s.V60_EDUCATION,
        t.EMPLOYMENT_STATUS           = s.V64_EMPLOYMENT_STATUS,
        t.OCCUPATION                  = s.V65_OCCUPATION,
        t.WORKERS_UNION               = s.V74_WORKERS_UNION
WHEN NOT MATCHED THEN
    INSERT
    VALUES (RESPONDENT_ID,
            STUDY_ID,
            V4A_EAST_WEST,
            CASE WHEN V75_STATE < 0 THEN NULL ELSE V75_STATE END,
            V27_FINANCIAL_STANDING,
            V28_FINANCIAL_STANDING_FORECAST,
            V52_RELIGION,
            V54_GENDER,
            V55_AGE,
            V57_MARITAL_STATUS,
            V60_EDUCATION,
            V64_EMPLOYMENT_STATUS,
            V65_OCCUPATION,
            V74_WORKERS_UNION)