OPEN SCHEMA NOAH_JUTZ;

-- Merge from st_meta_bundestag_parties

MERGE INTO PARTY t
USING ( SELECT SHORTNAME, MAX(NAME) AS NAME
        FROM ST_META_BUNDESTAG_PARTIES
        GROUP BY SHORTNAME
    ) AS s
ON t.SHORTNAME = s.SHORTNAME
WHEN MATCHED THEN
    UPDATE
    SET FULL_NAME = NAME
WHEN NOT MATCHED THEN
    INSERT
        (SHORTNAME, FULL_NAME)
    VALUES (SHORTNAME, NAME);
