OPEN SCHEMA NOAH_JUTZ;

MERGE INTO RESPONDENT t
USING (
    SELECT RESPONDENT_ID,
           STUDY_ID,
           V4A_EAST_WEST,
           CASE WHEN V75_STATE >= 0 THEN V75_STATE END                           AS V75_STATE,
           CASE WHEN V27_FINANCIAL_STANDING >= 0 THEN V27_FINANCIAL_STANDING END AS V27_FINANCIAL_STANDING,
           CASE
               WHEN V28_FINANCIAL_STANDING_FORECAST >= 0
                   THEN V28_FINANCIAL_STANDING_FORECAST END                      AS V28_FINANCIAL_STANDING_FORECAST,
           CASE WHEN V52_RELIGION >= 0 THEN V52_RELIGION END                     AS V52_RELIGION,
           CASE WHEN V54_GENDER >= 0 THEN V54_GENDER END                         AS V54_GENDER,
           CASE WHEN V55_AGE >= 0 THEN V55_AGE END                               AS V55_AGE,
           CASE WHEN V57_MARITAL_STATUS >= 0 THEN V57_MARITAL_STATUS END         AS V57_MARITAL_STATUS,
           CASE WHEN V60_EDUCATION >= 0 THEN V60_EDUCATION END                   AS V60_EDUCATION,
           CASE WHEN V64_EMPLOYMENT_STATUS >= 0 THEN V64_EMPLOYMENT_STATUS END   AS V64_EMPLOYMENT_STATUS,
           CASE WHEN V65_OCCUPATION >= 0 THEN V65_OCCUPATION END                 AS V65_OCCUPATION,
           CASE WHEN V74_WORKERS_UNION >= 0 THEN V74_WORKERS_UNION END           AS V74_WORKERS_UNION,
           (RESPONDENT_ID * 10000000) + (V4A_EAST_WEST * 1000000) + STUDY_ID AS NEW_RESPONDENT_ID
    FROM ST_POLITBAROMETER_SURVEY
    WHERE V4A_EAST_WEST > 0
    QUALIFY ROW_NUMBER() OVER (PARTITION BY RESPONDENT_ID, STUDY_ID, V4A_EAST_WEST) = 1
    ) AS s
ON t.RESPONDENT_ID = s.NEW_RESPONDENT_ID
    WHEN MATCHED THEN
    UPDATE
    SET t.BUNDESLAND_ID               = CASE WHEN V75_STATE < 0 THEN NULL ELSE V75_STATE END,
        t.FINANCIAL_STANDING          = s.V27_FINANCIAL_STANDING,
        t.FINANCIAL_STANDING_FORECAST = s.V28_FINANCIAL_STANDING_FORECAST,
        t.RELIGION                    = s.V52_RELIGION,
        t.GENDER                      = s.V54_GENDER,
        t.AGE                         = s.V55_AGE,
        t.MARITAL_STATUS              = s.V57_MARITAL_STATUS,
        t.EDUCATION                   = s.V60_EDUCATION,
        t.EMPLOYMENT_STATUS           = s.V64_EMPLOYMENT_STATUS,
        t.OCCUPATION                  = s.V65_OCCUPATION,
        t.WORKERS_UNION               = s.V74_WORKERS_UNION
WHEN NOT MATCHED THEN
    INSERT
    VALUES (s.NEW_RESPONDENT_ID,
            V4A_EAST_WEST,
            CASE WHEN V75_STATE < 0 THEN NULL ELSE V75_STATE END,
            V27_FINANCIAL_STANDING,
            V28_FINANCIAL_STANDING_FORECAST,
            V52_RELIGION,
            V54_GENDER,
            V55_AGE,
            V57_MARITAL_STATUS,
            V60_EDUCATION,
            V64_EMPLOYMENT_STATUS,
            V65_OCCUPATION,
            V74_WORKERS_UNION)