OPEN SCHEMA NOAH_JUTZ;

MERGE INTO BUNDESTAG_ELECTION_CENSUS t
USING (
    SELECT DISTINCT INTYEAR,
                    DISTRICT_ID,
                    VOTING_ELIGIBLE_POPULATION,
                    VOTERS,
                    VALID_VOTES,
                    INVALID_VOTES,
                    TO_DATE(TO_CHAR(INTYEAR), 'YYYY') AS INTYEAR_DATE
    FROM ST_BUNDESTAG_ELECTIONS
    ) AS s
ON t.term = s.INTYEAR_DATE AND t.DISTRICT_ID = s.DISTRICT_ID
WHEN MATCHED THEN
    UPDATE
    SET t.VOTING_ELIGIBLE_POPULATION = s.VOTING_ELIGIBLE_POPULATION,
        t.VOTERS                     = s.VOTERS,
        t.VALID_VOTES                = s.VALID_VOTES,
        t.INVALID_VOTES              = s.INVALID_VOTES
WHEN NOT MATCHED THEN
    INSERT
    VALUES (TO_DATE(TO_CHAR(s.INTYEAR), 'YYYY'),
            s.DISTRICT_ID,
            s.VOTING_ELIGIBLE_POPULATION,
            s.VOTERS,
            s.VALID_VOTES,
            s.INVALID_VOTES);

SELECT DISTINCT s.DISTRICT_ID
FROM ST_BUNDESTAG_ELECTIONS s
WHERE s.DISTRICT_ID NOT IN (SELECT voting_district_id FROM Voting_District);

-- check voting districts that are not in VOTING_DISTRICT table
SELECT
    b.n,
    a.VOTING_DISTRICT_ID
FROM (
    SELECT ROW_NUMBER() OVER (ORDER BY 1) AS n
    FROM EXA_ALL_COLUMNS
    LIMIT 300
) b
LEFT JOIN (
    SELECT DISTINCT VOTING_DISTRICT_ID
    FROM VOTING_DISTRICT
) a
    ON a.VOTING_DISTRICT_ID = b.n
ORDER BY b.n;