CREATE SCHEMA noah;
OPEN SCHEMA noah;
CREATE TABLE users (name VARCHAR(2000));
INSERT INTO users VALUES ('noah');
SELECT ROWNUM, ROWID, * FROM users;
DELETE FROM users WHERE ROWID = 36893488147419103232;

SELECT CURRENT_SESSION;

GRANT CREATE SESSION TO PUBLIC;
REVOKE CREATE SESSION FROM PUBLIC;

SELECT * FROM sys.EXA_ALL_OBJ_PRIVS;
SELECT * FROM sys.EXA_ALL_TABLES;